
import React, { useEffect, useState } from 'react';
import { BarChart, Calendar, TrendingUp } from 'lucide-react';

const Progress = () => {
    const [stats, setStats] = useState({ study_hours: 0, quizzes_taken: 0, streak_days: 0 });
    const [chartImage, setChartImage] = useState(null);

    useEffect(() => {
        fetch('/api/progress')
            .then(res => res.json())
            .then(data => setStats(data))
            .catch(err => console.error("Error fetching progress:", err));

        fetch('/api/analytics/dashboard')
            .then(res => res.json())
            .then(data => {
                if (data.chart) setChartImage(`data:image/png;base64,${data.chart}`);
            })
            .catch(err => console.error("Error fetching chart:", err));
    }, []);

    const resetStats = async () => {
        if (!confirm("Reset all study progress?")) return;
        await fetch('/api/progress', { method: 'DELETE' });
        setStats({ study_hours: 0, quizzes_taken: 0, streak_days: 0 });
    };

    return (
        <div className="pt-24 pb-12 min-h-screen bg-slate-50">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="mb-12 flex justify-between items-end">
                    <div>
                        <h1 className="text-4xl font-bold text-slate-900 mb-4">Your Progress</h1>
                        <p className="text-xl text-slate-600">Track your study habits and improvements over time.</p>
                    </div>
                    <button onClick={resetStats} className="text-red-500 hover:text-red-700 text-sm font-semibold">
                        Reset Data
                    </button>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                        <div className="flex items-center gap-4 mb-4">
                            <div className="p-3 bg-blue-100 rounded-xl text-blue-600"><TrendingUp className="w-6 h-6" /></div>
                            <h3 className="font-bold text-slate-900">Active Days</h3>
                        </div>
                        <p className="text-4xl font-black text-slate-900">{stats.streak_days} <span className="text-lg font-medium text-slate-500">days</span></p>
                    </div>
                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                        <div className="flex items-center gap-4 mb-4">
                            <div className="p-3 bg-green-100 rounded-xl text-green-600"><Calendar className="w-6 h-6" /></div>
                            <h3 className="font-bold text-slate-900">Hours Studied</h3>
                        </div>
                        <p className="text-4xl font-black text-slate-900">{stats.study_hours} <span className="text-lg font-medium text-slate-500">hours</span></p>
                    </div>
                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                        <div className="flex items-center gap-4 mb-4">
                            <div className="p-3 bg-amber-100 rounded-xl text-amber-600"><BarChart className="w-6 h-6" /></div>
                            <h3 className="font-bold text-slate-900">Quizzes Taken</h3>
                        </div>
                        <p className="text-4xl font-black text-slate-900">{stats.quizzes_taken} <span className="text-lg font-medium text-slate-500">quizzes</span></p>
                    </div>
                </div>

                <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 flex flex-col items-center justify-center min-h-[400px] text-center overflow-hidden">
                    {chartImage ? (
                        <>
                            <h3 className="text-xl font-bold text-slate-900 mb-6 self-start">Study Analytics (Generated by Python/Pandas)</h3>
                            <img src={chartImage} alt="Python Generated Chart" className="max-w-full rounded-xl shadow-lg border border-slate-100" />
                        </>
                    ) : (
                        <>
                            <img src="https://placehold.co/600x300/e2e8f0/94a3b8?text=Generating+Python+Chart..." alt="Chart Placeholder" className="rounded-xl mb-6 opacity-50" />
                            <h3 className="text-xl font-bold text-slate-900 mb-2">No Data Yet</h3>
                            <p className="text-slate-500 max-w-md">Complete a quiz or study session to see your Python-generated analytics.</p>
                        </>
                    )}
                </div>
            </div>
        </div>
    );
};

export default Progress;
